import Head from 'next/head'
import styles from '../styles/Home.module.css'

import { useAuth } from '../lib/auth';
import { useRouter } from 'next/router';

import { useEffect } from 'react';

export default function Home() {

  const router = useRouter()
  const { user, signinWithGoogle } = useAuth();

  useEffect(() => {
    if (user) {
      router.push('/conversations');
    }
  }, [user])

  return (
    <div className={styles.container}>
      <Head>
        <title>Messagerie babbel</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/babel.ico" />
      </Head>

      <main className={styles.main}>
        <h1>Messagerie Babbel</h1>
        <div className={styles.login}>
          <h2>Login</h2>
          <button
            onClick={signinWithGoogle}
          >
            Sign in with google
          </button>
        </div>
      </main>
    </div>
  )
}
